name: PR Build

on:
  pull_request:
    branches:
      - main
      - release/*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven (+ unit tests only)
        run: mvn clean test

      - name: Integration tests
        run: mvn verify -P integration-tests
        env:
          GIGACHAT_API_CLIENT_ID: ${{ secrets.GIGACHAT_API_CLIENT_ID }}
          GIGACHAT_API_CLIENT_SECRET: ${{ secrets.GIGACHAT_API_CLIENT_SECRET }}
          GIGACHAT_API_SCOPE: ${{ secrets.GIGACHAT_API_SCOPE }}
